-- First, remove the table if it exists
drop table if exists websites;

-- Create the table anew
CREATE TABLE websites (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  html TEXT NOT NULL,
  abstract TEXT,
  rating INTEGER DEFAULT 3
);

-- insert some test data
-- Using a multi-row insert statement here
insert into websites 
    (title, html, abstract, rating)
    values
        ('Google', 'http://www.google.com', 'search website', 3),
        ('YouTube', 'http://www.youtube.com', 'video website', 5),
        ('Twitter', 'http://www.twitter.com', 'social media', 2);